### ISSUE TITLE
Evaluation from vetcyb23-autumn link meeting 2023-11-16

### ISSUE THREAD

**Issue by dbosk** [OpenSecEd/scientific-method#26]
# AK2030

- The structure and contents is good.
- Flexible about when one can do the material, lectures and seminars.
- The course isn't that related to CS/Security. The examples are hard to relate to CS/Security. Can one use one seminar or adapt the seminars to focus on how do these methods relate to the CS/Security field?
- Seminars are good otherwise.

## Ideas:
- Simulations and physical experiments building bridges, how does that relate to CS/Security?
- We do that in security too, for instance simulate the Tor network. As opposed to collecting real Tor traffic.
- [ ] #29

## Todo:
- [ ] Look into AK2030 to check what needs clarification as to how to be applied in IT/CS/Security. See #28.
- [ ] Maybe add scenarios before module to motivate and then clarification afterwards. See #28.

# DA2215 Science of Security

- Most students were disappointed with the structure of the course.
- They didn't know what they were supposed to learn. Even after asking.
- Didn't bridge the gap, the things from AK2023 wasn't applicable in DA2215.
- Students were upset about the short notice for the final seminar and the prep assignment.
- Lack of communication of about what to do.
- Didn't have time to sync.
- Also didn't have the sync in mind when discussing with Sonja and Mathias.

## Idea
- [ ] Pick out the most important things from AK2030 and highlight them and why they're important to us. See #28.

**Comment by dbosk** [comment]
Date: Thu, 16 Nov 2023 14:12:59 +0100
To: Daniel Bosk <dbosk@kth.se>
Subject: Feedback DA2215
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=utf-8

   Här är sammanfattningen av feedbacken vi fått:

     * Many students are disappointed in the structure of this course. They
       complained that they did not know what they were supposed to learn
       even after the course had been completed.

     * The communication in this course was also lacking according to many
       students. It was not clear until two weeks before the end of the
       course (during the exam period) what the final assignment would be and
       students felt surprised and unprepared for it when it was announced.
       Students also complained that there was lacking communication
       regarding what we were supposed to learn from the course material and
       the seminars. The amount of material provided ahead of the seminars
       was too much to focus on without clear instructions.

     * Course content seemed unfinished and this heavily impaired students'
       learning ability.
